import { useEffect, useState } from "react";
import {
    Activity,
    Zap,
    Gauge,
    Thermometer,
    Radio,
    CheckCircle2,
    ArrowRight,
    BrainCircuit,
} from "lucide-react";
import { useNavigate } from "react-router-dom";
import "../styles/measurements.css";

function Measurements() {
    const navigate = useNavigate();

    const [running, setRunning] = useState(true);
    const [diagnosis, setDiagnosis] = useState(null);

    const [values, setValues] = useState({
        inputVoltage: 12.02,
        outputVoltage: 5.01,
        current: 0.18,
        temperature: 29.4,
    });

    // Simulated electrical measurements.
    // These will later be replaced by ESP32 measurements.
    useEffect(() => {
        if (!running) return;

        const interval = setInterval(() => {
            setValues({
                inputVoltage: +(12 + (Math.random() * 0.08 - 0.04)).toFixed(2),
                outputVoltage: +(5 + (Math.random() * 0.06 - 0.03)).toFixed(2),
                current: +(0.18 + (Math.random() * 0.04 - 0.02)).toFixed(2),
                temperature: +(29.4 + (Math.random() * 0.8 - 0.4)).toFixed(1),
            });
        }, 1500);

        return () => clearInterval(interval);
    }, [running]);

    // Load AI diagnosis generated during the New PCB Test.
    useEffect(() => {
        const savedDiagnosis = sessionStorage.getItem("pcbDiagnosis");

        if (savedDiagnosis) {
            try {
                setDiagnosis(JSON.parse(savedDiagnosis));
            } catch (error) {
                console.error("Failed to load AI diagnosis:", error);
            }
        }
    }, []);

    const continueToDiagnosis = () => {
        // Save the latest simulated measurements.
        sessionStorage.setItem(
            "pcbMeasurements",
            JSON.stringify(values)
        );

        navigate("/diagnosis");
    };

    return (
        <div className="measurements-page">

            {/* HEADER */}
            <div className="measurements-header">
                <div>
                    <span className="eyebrow">ELECTRICAL TEST</span>

                    <h2>Live Measurements</h2>

                    <p>
                        Real-time electrical and temperature measurements
                        from the PCB.
                    </p>
                </div>

                <div className="acquisition-status">
                    <span className="pulse-dot"></span>
                    {running
                        ? "DATA ACQUISITION ACTIVE"
                        : "DATA ACQUISITION PAUSED"}
                </div>
            </div>

            {/* SIMULATION NOTICE */}
            <div
                style={{
                    marginBottom: "20px",
                    padding: "14px 18px",
                    borderRadius: "12px",
                    background: "#fff7ed",
                    border: "1px solid #fed7aa",
                    color: "#9a3412",
                    display: "flex",
                    alignItems: "center",
                    gap: "10px",
                    fontSize: "14px",
                }}
            >
                <Activity size={18} />

                <span>
                    <strong>Simulation Mode:</strong>{" "}
                    measurements are currently generated by software.
                    ESP32 hardware will be integrated later.
                </span>
            </div>

            {/* PROGRESS */}
            <div className="measurement-progress">

                <div className="progress-top">
                    <div>
                        <strong>
                            Automated PCB Test in Progress
                        </strong>

                        <span>
                            Collecting measurements from configured test
                            points
                        </span>
                    </div>

                    <strong>68%</strong>
                </div>

                <div className="progress-bar">
                    <div className="progress-fill"></div>
                </div>

                <div className="progress-info">
                    <span>Test Point 7 of 10</span>
                    <span>Software Simulation → FastAPI → AI</span>
                </div>

            </div>

            {/* MEASUREMENT CARDS */}
            <div className="measurement-grid">

                {/* INPUT VOLTAGE */}
                <div className="measurement-card">

                    <div className="measurement-card-top">
                        <div className="measurement-icon blue">
                            <Zap size={21} />
                        </div>

                        <span className="normal-badge">
                            NORMAL
                        </span>
                    </div>

                    <span className="measurement-label">
                        INPUT VOLTAGE
                    </span>

                    <strong>
                        {values.inputVoltage}
                        <small> V</small>
                    </strong>

                    <p>
                        Expected: 11.5 – 12.5 V
                    </p>

                </div>

                {/* OUTPUT VOLTAGE */}
                <div className="measurement-card">

                    <div className="measurement-card-top">
                        <div className="measurement-icon green">
                            <Gauge size={21} />
                        </div>

                        <span className="normal-badge">
                            NORMAL
                        </span>
                    </div>

                    <span className="measurement-label">
                        OUTPUT VOLTAGE
                    </span>

                    <strong>
                        {values.outputVoltage}
                        <small> V</small>
                    </strong>

                    <p>
                        Expected: 4.8 – 5.2 V
                    </p>

                </div>

                {/* CURRENT */}
                <div className="measurement-card">

                    <div className="measurement-card-top">
                        <div className="measurement-icon purple">
                            <Activity size={21} />
                        </div>

                        <span className="normal-badge">
                            NORMAL
                        </span>
                    </div>

                    <span className="measurement-label">
                        CURRENT
                    </span>

                    <strong>
                        {values.current}
                        <small> A</small>
                    </strong>

                    <p>
                        Expected: &lt; 0.50 A
                    </p>

                </div>

                {/* TEMPERATURE */}
                <div className="measurement-card">

                    <div className="measurement-card-top">
                        <div className="measurement-icon orange">
                            <Thermometer size={21} />
                        </div>

                        <span className="normal-badge">
                            NORMAL
                        </span>
                    </div>

                    <span className="measurement-label">
                        TEMPERATURE
                    </span>

                    <strong>
                        {values.temperature}
                        <small> °C</small>
                    </strong>

                    <p>
                        Expected: &lt; 60 °C
                    </p>

                </div>

            </div>

            {/* TEST POINTS */}
            <div className="measurement-main-grid">

                <div className="panel measurement-table-panel">

                    <div className="panel-heading">

                        <div>
                            <h3>
                                Test Point Measurements
                            </h3>

                            <p>
                                Electrical values acquired through the
                                multiplexer
                            </p>
                        </div>

                        <span className="live-label">
                            <span></span>
                            LIVE
                        </span>

                    </div>

                    <div className="table-wrapper">

                        <table>

                            <thead>
                                <tr>
                                    <th>POINT</th>
                                    <th>LOCATION</th>
                                    <th>VOLTAGE</th>
                                    <th>RESISTANCE</th>
                                    <th>STATUS</th>
                                </tr>
                            </thead>

                            <tbody>

                                <tr>
                                    <td className="point-name">
                                        TP1
                                    </td>

                                    <td>
                                        Input Supply
                                    </td>

                                    <td>
                                        {values.inputVoltage} V
                                    </td>

                                    <td>—</td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td className="point-name">
                                        TP2
                                    </td>

                                    <td>
                                        After D1
                                    </td>

                                    <td>
                                        11.31 V
                                    </td>

                                    <td>—</td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td className="point-name">
                                        TP3
                                    </td>

                                    <td>
                                        LM7805 Input
                                    </td>

                                    <td>
                                        11.29 V
                                    </td>

                                    <td>—</td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td className="point-name">
                                        TP4
                                    </td>

                                    <td>
                                        LM7805 Output
                                    </td>

                                    <td>
                                        {values.outputVoltage} V
                                    </td>

                                    <td>—</td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td className="point-name">
                                        TP5
                                    </td>

                                    <td>
                                        C1 Section
                                    </td>

                                    <td>
                                        5.02 V
                                    </td>

                                    <td>
                                        1.02 kΩ
                                    </td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                                <tr>
                                    <td className="point-name">
                                        TP6
                                    </td>

                                    <td>
                                        Output Section
                                    </td>

                                    <td>
                                        5.01 V
                                    </td>

                                    <td>
                                        980 Ω
                                    </td>

                                    <td>
                                        <span className="table-normal">
                                            Normal
                                        </span>
                                    </td>
                                </tr>

                            </tbody>

                        </table>

                    </div>

                </div>

                {/* HARDWARE STATUS */}
                <div className="panel hardware-panel">

                    <div className="panel-heading">

                        <div>
                            <h3>
                                Acquisition Hardware
                            </h3>

                            <p>
                                Hardware integration status
                            </p>
                        </div>

                    </div>

                    <div className="hardware-list">

                        <div className="hardware-item">
                            <Radio size={18} />

                            <div>
                                <strong>
                                    ESP32 DevKit V1
                                </strong>

                                <span>
                                    Awaiting hardware integration
                                </span>
                            </div>

                            <span
                                style={{
                                    fontSize: "11px",
                                    fontWeight: "700",
                                    color: "#d97706",
                                }}
                            >
                                SIM
                            </span>
                        </div>

                        <div className="hardware-item">
                            <Activity size={18} />

                            <div>
                                <strong>
                                    ADS1115 ADC
                                </strong>

                                <span>
                                    Awaiting hardware integration
                                </span>
                            </div>

                            <span
                                style={{
                                    fontSize: "11px",
                                    fontWeight: "700",
                                    color: "#d97706",
                                }}
                            >
                                SIM
                            </span>
                        </div>

                        <div className="hardware-item">
                            <Zap size={18} />

                            <div>
                                <strong>
                                    INA219
                                </strong>

                                <span>
                                    Awaiting hardware integration
                                </span>
                            </div>

                            <span
                                style={{
                                    fontSize: "11px",
                                    fontWeight: "700",
                                    color: "#d97706",
                                }}
                            >
                                SIM
                            </span>
                        </div>

                        <div className="hardware-item">
                            <Gauge size={18} />

                            <div>
                                <strong>
                                    CD74HC4067
                                </strong>

                                <span>
                                    Awaiting hardware integration
                                </span>
                            </div>

                            <span
                                style={{
                                    fontSize: "11px",
                                    fontWeight: "700",
                                    color: "#d97706",
                                }}
                            >
                                SIM
                            </span>
                        </div>

                        <div className="hardware-item">
                            <Thermometer size={18} />

                            <div>
                                <strong>
                                    DS18B20
                                </strong>

                                <span>
                                    Awaiting hardware integration
                                </span>
                            </div>

                            <span
                                style={{
                                    fontSize: "11px",
                                    fontWeight: "700",
                                    color: "#d97706",
                                }}
                            >
                                SIM
                            </span>
                        </div>

                    </div>

                </div>

            </div>

            {/* AI STATUS */}
            <div
                style={{
                    marginTop: "22px",
                    padding: "20px",
                    background: "white",
                    border: "1px solid #e2e8f0",
                    borderRadius: "16px",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "space-between",
                    gap: "20px",
                }}
            >
                <div
                    style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "13px",
                    }}
                >
                    <div
                        style={{
                            width: "42px",
                            height: "42px",
                            borderRadius: "12px",
                            background: "#f1f5f9",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                        }}
                    >
                        <BrainCircuit size={21} />
                    </div>

                    <div>
                        <strong>
                            AI Diagnosis
                        </strong>

                        <p
                            style={{
                                margin: "4px 0 0",
                                color: "#64748b",
                                fontSize: "13px",
                            }}
                        >
                            {diagnosis
                                ? "AI diagnosis result available"
                                : "No diagnosis result available yet"}
                        </p>
                    </div>
                </div>

                {diagnosis && (
                    <span
                        style={{
                            padding: "8px 12px",
                            borderRadius: "999px",
                            background: "#ecfdf5",
                            color: "#047857",
                            fontSize: "12px",
                            fontWeight: "700",
                        }}
                    >
                        RESULT READY
                    </span>
                )}
            </div>

            {/* ACTION */}
            <div className="measurement-action">

                <div>
                    <strong>
                        Electrical data collection complete?
                    </strong>

                    <p>
                        Continue to AI analysis when all required
                        measurements are available.
                    </p>
                </div>

                <div className="action-buttons">

                    <button
                        className="stop-btn"
                        onClick={() => setRunning(!running)}
                    >
                        {running
                            ? "Pause Acquisition"
                            : "Resume Acquisition"}
                    </button>

                    <button
                        className="analysis-btn"
                        onClick={continueToDiagnosis}
                    >
                        Continue to AI Diagnosis
                        <ArrowRight size={17} />
                    </button>

                </div>

            </div>

        </div>
    );
}

export default Measurements;